In [7]:
# import libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
# laoding dataset
from google.colab import files as f
f.upload()

In [13]:
df_train = pd.read_csv("1000_Companies.csv")
df_train.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [14]:
# remove last column

Y = df_train.pop("Profit")
X = df_train # set features as remaining elements

In [15]:
X.head()

   R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [16]:
Y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [17]:
# extract as numpy
X = X.values
Y = Y.values

In [18]:
X.shape

(1000, 4)

In [19]:
# encoding categorical data

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

transformer = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[3])],remainder= "passthrough")

# Apply Transformation
X = transformer.fit_transform(X)

In [22]:
print(X[:3])

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]]

In [23]:
# preventing multicolinearity

X = X[:, 1:]

In [24]:

# Data splits

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

# Model Regression

In [25]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [26]:
# fitting train data

model.fit(X_train,y_train)

LinearRegression()

In [27]:
# model evaluation
y_pred = model.predict(X_test)

In [30]:
# observing weights assigned to feature columns
model.coef_

array([-8.80536598e+02, -6.98169073e+02,  5.25845857e-01,  8.44390881e-01,
        1.07574255e-01])

In [31]:
model.intercept_

np.float64(-51035.229724047706)

In [33]:
# R square
model.score(X_test, y_test)

0.9112695892268908

In [38]:
# calculating the r squared value

from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.9112695892268908

# R2

Out of the total variance how much does the linear regression manage to explain or cover. The spaces or percentages left are the spread between the actual data points and the the predicted values